let api = Router::new()
        .route("/auth/register", post(handlers::auth::register))
        .route("/auth/login", post(handlers::auth::login))
        .route("/auth/refresh", post(handlers::auth::refresh))
        .route("/auth/me", get(handlers::auth::me))
        .route("/users/me/zetra-id", get(handlers::users::me_zetra_id))
        .route("/users/:id", get(handlers::users::get_user))
        .route("/comments", get(handlers::comments::list).post(handlers::comments::create))
        .route("/comments/:id", delete(handlers::comments::delete))
        .route("/media/image", post(handlers::media::upload_image))
        .route("/media/video", post(handlers::media::upload_video));
